Models/BloodLevel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FYP_Blood.Models
{
    public class BloodLevel
    {
        public string bloodlvlid { get; set; }
        public string userid { get; set; }
        public string datecollected { get; set; }
        public int bloodqty { get; set; }
        public string hosname { get; set; }
        public string department { get; set; }

    }
}

Models/BloodQuality.cs
using Nethereum.ABI.FunctionEncoding.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Web;

namespace FYP_Blood.Models
{
    [FunctionOutput]
    public class BloodQuality
    {
        [Parameter("uint256", "bloodqualityid", 1)]
        public BigInteger bloodqualityid { get; set; }

        [Parameter("uint256", "donorid", 2)]
        public BigInteger donorid { get; set; }

        [Parameter("uint256", "hosid", 3)]
        public BigInteger hosid { get; set; }

        [Parameter("string", "result", 4)]
        public string result { get; set; }

    }
}

Controllers/HospitalController.cs
using FYP_Blood.Models;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Nethereum.Web3;
using Nethereum.Contracts;
using Nethereum.ABI.FunctionEncoding.Attributes;
using System.Threading.Tasks;
using System.Web.Script.Serialization;
using System.IO;
using ZXing;
using System.Drawing;
using System.Drawing.Imaging;
using System.Configuration;
using System.Data.SqlClient;
using Microsoft.Reporting.WebForms;

namespace FYP_Blood.Controllers
{
    public class HospitalController : Controller
    {
        Database_Access_Layer.db dblayer = new Database_Access_Layer.db();
        BloodLevel bl = new BloodLevel();

        public ActionResult HospitalLogOut()
        {
            if (!string.IsNullOrEmpty(Session["user"] as string))
            {
                Session["user"] = null;
                Session.Abandon();
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return RedirectToAction("PageNotFound", "Home");
            }
        }

        public ActionResult Dashboard()
        {
            if (Convert.ToString(Session["userrole"]) == "Hospital Authority")
            {
                //latest 11nov
                var userId = Session["userid"];
                //


                List<Models.Event> eventList = new List<Models.Event>();

                String CS = ConfigurationManager.ConnectionStrings["con"].ConnectionString;
                using (SqlConnection con = new SqlConnection(CS))
                {
                    string query = "SELECT * FROM Event WHERE userId = @userId";
                    SqlCommand sqlcomm = new SqlCommand(query, con);
                    sqlcomm.Parameters.AddWithValue("@userId", userId);
                    con.Open();

                    //string query = "SELECT * FROM Event ";
                    //SqlCommand sqlcomm = new SqlCommand(query, con);
                    //con.Open();

                    SqlDataReader rdr = sqlcomm.ExecuteReader();
                    while (rdr.Read())
                    {
                        var eventDetail = new Models.Event();
                        eventDetail.e_id = Convert.ToInt32(rdr["e_id"]);
                        eventDetail.e_date = Convert.ToDateTime(rdr["e_date"]);
                        eventDetail.e_location = rdr["e_location"].ToString();
                        eventDetail.e_startTime = Convert.ToDateTime(rdr["e_startTime"].ToString());
                        eventDetail.e_endTime = Convert.ToDateTime(rdr["e_endTime"].ToString());
                        eventDetail.e_address = rdr["e_address"].ToString();
                        string query1 = "SELECT COUNT(userId) FROM Appointment WHERE e_id = @e_id";
                        SqlCommand sqlcomm1 = new SqlCommand(query1, con);
                        sqlcomm1.Parameters.AddWithValue("e_id", eventDetail.e_id);
                        int rowsAmount = (int)sqlcomm1.ExecuteScalar();
                        //****set the webconfig MultipleActiveResultSets=True; already to allow new sql in one reader
                        eventDetail.registeredUserCount = rowsAmount;

                        string query2 = "SELECT COUNT(*) FROM Event";
                        SqlCommand sqlcomm2 = new SqlCommand(query2, con);
                        int eventCount = (int)sqlcomm2.ExecuteScalar();
                        eventDetail.eventCount = eventCount;

                        eventList.Add(eventDetail);
                    }
                    rdr.Close();
                    con.Close();
                }
                return View(eventList);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        /*-----------------------------------------------BLOOD LEVEL------------------------------------------ */

        public ActionResult BloodLevel()
        {
            if (Convert.ToString(Session["userrole"]) == "Hospital Authority")
            {
                return View();
            }
            else
            {
                return RedirectToAction("PageUnauthorised", "Home");
            }
                
        }

        //Blood Level Module
        public ActionResult GetBloodLevel()
        {
            try
            {
                string currentname = Convert.ToString(Session["user"]);
                string currentid = Convert.ToString(Session["userid"]);
                List<BloodLevel> bloodLvl = dblayer.GetBloodLevel(currentname);

                return Json(bloodLvl, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw new Exception("Error on loading blood level listing..." + ex.Message);
            }

        }

        public ActionResult UpdateBloodLevel(string bloodlvldate, int bloodlvlqty)
        {
            try
            {
                string currentid = Convert.ToString(Session["userid"]);
                dblayer.UpdateBloodLevel(bloodlvldate, bloodlvlqty, currentid);
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.OK);
            }
            catch (Exception ex)
            {
                throw new Exception("Error on Updating Blood Level" + ex.Message);
            }
        }

        /*-----------------------------------------------APPOINTMENT------------------------------------------ */

        public ActionResult ValidateAptId(int _aptid)
        {
            int result = dblayer.ValidateAptId(_aptid);
            return Json(result, JsonRequestBehavior.AllowGet);
        }


        //Update Appointment ID Blood result status to completed
        public void UpdateAptResult(int _aptid)
        {
            try
            {
                dblayer.UpdateAptResult(_aptid);
            }
            catch (Exception ex)
            {
                throw new Exception("Error on saving appointment update blood result " + ex.Message);
            }

        }

        //Generate QR Code 
        //[HttpPost]
        public void Generate(string _donorid)
        {
            QRCodeModel qrcode = new QRCodeModel();
            try
            {
                qrcode.QRCodeImagePath = GenerateQRCode(_donorid);
                //TempData["Imagename"] = Server.MapPath("~") + "image/QrCode.jpg"; //qrcode.QRCodeImagePath;

            }
            catch (Exception ex)
            {
                throw new Exception("Error on showing qrcode" + ex.Message);
            }
        }

        private string GenerateQRCode(string qrcodeText)
        {
            string folderPath = "~/image/";
            string imagePath = "~/image/QrCode.jpg";

            //if the directory doesnt exist then create it.
            if (!Directory.Exists(Server.MapPath(folderPath)))
            {
                Directory.CreateDirectory(Server.MapPath(folderPath));
            }

            var barcodeWriter = new BarcodeWriter();
            barcodeWriter.Format = BarcodeFormat.QR_CODE;
            //convert param string into image
            var result = barcodeWriter.Write(qrcodeText);

            string barcodePath = Server.MapPath(imagePath);
            var barcodeBitmap = new Bitmap(result);
            //copied into custom path "~/image/QrCode.jpg
            using (MemoryStream memory = new MemoryStream())
            {
                using (FileStream fs = new FileStream(barcodePath, FileMode.Create, FileAccess.ReadWrite))
                {
                    barcodeBitmap.Save(memory, ImageFormat.Jpeg);
                    byte[] bytes = memory.ToArray();
                    fs.Write(bytes, 0, bytes.Length);
                }
            }
            return imagePath;
        }

        /*-----------------------------------------------REPORTING------------------------------------------ */
        public ActionResult BloodReport()
        {
                //SSRS Report Without Parameter
                //string ssrsUrl = ConfigurationManager.AppSettings["SSRSReportsUrl"].ToString();
                //ReportViewer viewer = new ReportViewer();
                //viewer.ProcessingMode = ProcessingMode.Remote;
                //viewer.SizeToReportContent = true;
                //viewer.AsyncRendering = true;
                //viewer.ServerReport.ReportServerUrl = new Uri(ssrsUrl);
                //viewer.ServerReport.ReportPath = "/ReportBlood";

                //ViewBag.ReportViewer = viewer;
                return View();
        }

        [HttpPost]
        public ActionResult BloodReport(string startDate, string endDate)
        {
            if (Convert.ToString(Session["userrole"]) == "Hospital Authority")
            {
                string ssrsUrl = ConfigurationManager.AppSettings["SSRSReportsUrl"].ToString();
                ReportViewer viewer = new ReportViewer();
                viewer.ProcessingMode = ProcessingMode.Remote;
                viewer.SizeToReportContent = true;
                viewer.AsyncRendering = true;
                viewer.ServerReport.ReportServerUrl = new Uri(ssrsUrl);
                viewer.ServerReport.ReportPath = "/ReportBlood2";

                //String[] userValue = new string[] { startDate, endDate };
                ReportParameter param = new ReportParameter("StartDate");
                param.Name = "StartDate";
                param.Values.Add(startDate);
                viewer.ServerReport.SetParameters(param);
                ReportParameter secondparam = new ReportParameter("EndDate");
                secondparam.Name = "EndDate";
                secondparam.Values.Add(endDate);
                viewer.ServerReport.SetParameters(secondparam);


                ViewBag.ReportViewer = viewer;
                 return View("BloodReport");
            }
            else
            {
                return RedirectToAction("PageUnauthorised", "Home");
            }
        }
    }

}

Views/Hospital/BloodLevel.cshtml

@{
    ViewBag.Title = "BloodLevel";
    Layout = "~/Views/Shared/_HospitalLayout.cshtml";
}

<div class="main-content" style="height:64rem">
    <div class="container-fluid">
        <div class="row p-3">
            <h3><span class="authority-title">Blood Level Information Management</span></h3>
            <span class="authority-desc fw-bolder"> Manage hospital blood stock supply information.</span>
        </div>
        <div class="row">
            <div class="container card col-xl-10">
                <div class="row">
                    <div class="col">
                        <div class="m-3 authority-heading">New Blood Level Information</div>
                    </div>
                </div>
                <div class="row m-4">
                    <form name="bloodlvl" class="justify-content-start">
                        <div class="row">
                            <label for="hosNameDesc" class="col-sm-3 col-form-label formimput-desc">Hospital Name</label>
                            <div class="col-sm-3">
                                @Session["user"]
                            </div>
                            <label for="dateDesc" class="col-sm-2 col-form-label formimput-desc">Date</label>
                            <div class="col-sm-3">
                                <input class="form-control" type="date" date='dd-MM-yyyy' placeholder="DD/MM/YYYY" id="bloodDate" name="bloodDate" ng-model="bloodlvldate">
                            </div>
                        </div>
                        <div class="row pt-3">
                            <label for="bloodLvlDesc" class="col-sm-3 col-form-label formimput-desc">Blood Stock Quantity</label>
                            <div class="col-sm-3">
                                <input type="number" class="form-control" id="bloodQty" name="bloodQty" placeholder="Eg: 100" ng-model="bloodlvlqty" min="1" max="3000">
                            </div>
                        </div>
                        <div class="row d-flex justify-content-end">
                            <button class="btn-authority col-sm-2" ng-click="savebloodlvl(bloodlvldate, bloodlvlqty)">SAVE</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="row mt-3">
            <div class="container card col-xl-10" style="padding: 10px;">
                <div class="row">
                    <div class="col">
                        <div class="m-3 authority-heading">Current Blood Level Information</div>
                    </div>
                </div>
                <div class="row"> 
                    <table class="table" id="bloodlvltable" style="margin-top: 2.7rem;">
                        <thead style="background-color: #ebebeb; color: black;">
                            <tr>
                                <th scope="col" style="font-weight:500;">No.</th>
                                <th scope="col" style="font-weight:500;">ID</th>
                                <th scope="col" style="font-weight:500;">Authority ID</th>
                                <th scope="col" style="font-weight:500;">Department</th>
                                <th scope="col" style="font-weight:500;">Quantity</th>
                                <th scope="col" style="font-weight:500;">Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr ng-repeat="bloodlvl in bloodlvlrecord">
                                <td scope="row">{{$index +1}}</td>
                                <th>{{bloodlvl.bloodlvlid}}</th>
                                <td>{{bloodlvl.userid}}</td>
                                <td>{{bloodlvl.department}}</td>
                                <td>{{bloodlvl.bloodqty}}</td>
                                <td>{{bloodlvl.datecollected}}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Hospital/BloodQuality.cshtml

@{
    ViewBag.Title = "Blood Quality Management";
    Layout = "~/Views/Shared/_HospitalLayout.cshtml";
}

<div class="main-content">
    <div class="container-fluid">
        <div class="row p-3">
            <h3><span class="authority-title">Blood Quality Tracking</span></h3>
            <span class="authority-desc fw-bolder">Record blood pack testing result.</span>
        </div>
        <div class="row">
            <div class="container card col-xl-10" style="background-color: #F0F0F0">
                <div class="row">
                    <div class="col">
                        <div class="m-3">Please read carefully before updating the blood testing result into the system. : </div>
                    </div>
                </div>
                <div class="row m-4">
                    <ul>
                        <li>Blood+ system will use Blockchain technology to store and save the blood test result where the record is immutable once updated. </li>
                        <li>Please do take note that the record cannot be <b>CHANGED</b> or <b>EDITED</b> anymore once you confirm to save the record.</li>
                        <li>You are advised to check the details before confirming to save the record. </li>
                        <li>Your user ID will be recorded while saving the record.</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row mt-3">
            <div class="container card col-xl-10">
                <div class="row">
                    <div class="col">
                        <div class="m-3 authority-heading">Blood Pack Record</div>
                    </div>
                </div>
                <div class="row m-4">
                    <form name="save-quality-record-form" class="justify-content-start">
                        <div class="row">
                            <label class="col-sm-3 col-form-label formimput-desc">Hospital Authority ID</label>
                            <div class="col-sm-3 pt-2">
                                @Session["userid"]
                            </div>
                            <label class="col-sm-2 col-form-label formimput-desc">Hospital Name</label>
                            <div class="col-sm-3 pt-2">
                                @Session["user"]
                            </div>
                        </div>
                        <div class="row pt-3">
                            <label for="rstDonorId" class="col-sm-3 col-form-label formimput-desc">Appointment ID</label>
                            <div class="col-sm-3">
                                <input type="number" class="form-control" name="rstDonorId" id="rstDonorId" placeholder="Eg: 1043" ng-model="donorid" min="1">
                            </div>
                        </div>
                        <div class="row pt-3">
                            <label for="rstResult" class="col-sm-3 col-form-label formimput-desc">Status</label>
                            <div class="col-sm-3">
                                <select class="form-select col-sm-3" id="rstResult" data-ng-options="o.name for o in options" ng-model="rst.result"></select>
                            </div>
                        </div>
                        @*{{rst.result.name}}*@
                        <div class="row d-flex justify-content-end">
                            <button class="btn-authority col-sm-2" ng-click="savebloodquality(donorid, selectedOption)">SAVE</button>
                        </div>
                    </form>
                </div>
                </div>
            </div>
    </div>
</div>


Views/Hospital/BloodQuality_Listing.cshtml

@{
    ViewBag.Title = "Blood Quality";
    Layout = "~/Views/Shared/_HospitalLayout.cshtml";
}

@model FYP_Blood.Models.QRCodeModel

<div class="main-content">
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="row p-3 quality-listing-heading">
            <h3><span class="authority-title">Blood Quality Record</span></h3>
            <span class="authority-desc fw-bolder">View tested blood pack result where the status indicating the blood condition.</span>
        </div>

        <div class="row mt-3 mb-4 quality-listing-searchbox">
            <div class="container card col-xl-10">
                <form class="form-inline d-flex justify-content-center md-form form-sm mt-0" name="quality-records-form">
                    <div class="input-group rounded m-3">
                        <input type="search" class="form-control rounded" placeholder="Appointment ID" name="searchdonorid" id="searchdonorid" ng-model="searchdonorid" />
                    </div>
                    <button class="btn-authority col-sm-2" ng-click="searchbloodresult();">SEARCH</button>
                </form>
            </div>
        </div><hr />

        <div class="row p-3 quality-records-container" id="quality-records-container" style="display:none;">
            <span class="quality-records-desc">Search Result:</span>
            <div class="d-flex justify-content-center">
                <div class="row quality-records mt-4">
                    <div class="row col-md-6">
                        <span>
                            Blood Quality ID: @TempData["bqid"] <br />
                        </span>
                        <span class="mt-2">
                            Appointment ID: @TempData["donorid"]<br />
                        </span>
                        <span class="mt-2">
                            Authority ID: @TempData["hosid"]<br />
                        </span>
                        <span class="mt-2">
                            Result: @TempData["result"]<br />
                        </span>
                        <span class="mt-4">
                            <a href="javascript:window.print()" id="printlink">Click to Print Blood Pack Label</a>
                        </span>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="col-md-10  d-flex justify-content-end">
                                <img id="bloodqr" src="~/image/QrCode.jpg" alt="Image" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    window.onload = function () {
        var data = sessionStorage.getItem('clicked');
        if (data == 'true') {
            $("#quality-records-container").css("display", "block");
            sessionStorage.setItem('clicked', true);
        }
    };
</script>


Views/Hospital/BloodReport.cshtml
@using ReportViewerForMvc

@{
    ViewBag.Title = "BloodReport";
    Layout = "~/Views/Shared/_HospitalLayout.cshtml";
}

<div class="main-content" style="height:64rem">
    <div class="row p-3">
        <h3><span class="authority-title">Total Collected Blood Pack</span></h3>
        <span class="authority-desc fw-bolder">Summary report of collected blood pack</span>
    </div>
    <div class="container-fluid">
        @using (Html.BeginForm("BloodReport", "Hospital", FormMethod.Post))
        {

            <div class="row mb-4">
                <div class=" col-3">
                    <label for="startDate">Start Date</label>
                    <input type="date" class="form-control" id="startDate" name="startDate" />
                </div>
                <div class="col-3">
                    <label for="endDate">End Date</label>
                    <input type="date" class="form-control" id="endDate" name="endDate" />
                </div>
                <button type="submit" class="btn btn-primary col-3 viewReportBtn mt-4">SUBMIT</button>
            </div>
        }
   </div>

    @if (ViewBag.ReportViewer != null)
    {
        @Html.ReportViewer(ViewBag.ReportViewer as Microsoft.Reporting.WebForms.ReportViewer)
    }
</div>

Views/Hospital/Dashboard.cshtml
@model IEnumerable<FYP_Blood.Models.Event>

@{
    ViewBag.Title = "AuthorityDashboard";
    Layout = "~/Views/Shared/_HospitalLayout.cshtml";
    @*<link href="~/Content/Css/dashboardOverview.css" rel="stylesheet" />*@
}
<div class="main-content">
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="row p-3">
            <h3><span class="authority-title">Overview</span></h3>
        </div>

        <div class="row" style="margin-left: 212px">
            <!-- Dashboard Event Card -->
            <div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-first shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="summary-card-header fw-bolder text-uppercase mb-1">
                                    Ongoing Event
                                </div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">@Model.Count()</div>
                            </div>
                            <div class="col-auto">
                                <i class="bi bi-calendar-check fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Dashboard Blood Pack Card -->
            @*<div class="col-xl-3 col-md-6 mb-4">
                <div class="card border-left-second shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="summary-card-header fw-bolder text-uppercase mb-1">
                                    Blood Pack Received
                                </div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">1000</div>
                            </div>
                            <div class="col-auto">
                                <i class="bi bi-bookmarks fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>*@

        <div>
            <table class="eventTable" style="width:80%; margin-top:10px;" border ="1">
                @foreach (var ev in Model)
                {
                    <tr class="space"></tr>
                    <tr class="eventTitle">
                        <td class="image" rowspan="4" width="70px" align="center">
                            <img src="~/Content/images/BloodIcon1.png" />
                        </td>

                        <td width="400px" style="font-size:17px;"><b>@ev.e_location</b></td>

                        <td width="200px" rowspan="5" align="center">
                            @ev.registeredUserCount Registered
                        </td>
                    </tr>

                    <tr class="detail">
                        <td>@ev.e_date.ToString("MMMM dd,yyyy (ddd)")  @ev.e_startTime.ToString("hh:mm tt") - @ev.e_endTime.ToString("hh:mm tt")</td>
                    </tr>

                    <tr class="detail">
                        <td>@ev.e_address</td>
                    </tr>
                    <tr class="space"></tr>
                    <tr class="space"></tr>

                }

            </table>
        </div>
    </div>

</div>