Controllers/AuthorityController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using FYP_Blood.Models;
using System.Security.Cryptography;
using System.Text;

namespace FYP_Blood.Controllers
{
    public class AuthorityController : Controller
    {
        [HttpGet]
        public ActionResult CreateEvent()
        {
            if (Convert.ToString(Session["userrole"]) == "Hospital Authority")
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        public ActionResult CreateEvent(Event events)
        {
            if (Convert.ToString(Session["userrole"]) == "Hospital Authority")
            {
                //ADDED 16Nov2021 [WORK]
                var userId = Session["userid"];
                //

                if (ModelState.IsValid)
                { 
                    String CS = ConfigurationManager.ConnectionStrings["con"].ConnectionString;
                    using (SqlConnection con = new SqlConnection(CS))
                    {
                        //Added 16/11 [WORK]
                        string query = "Insert into Event(e_date,e_location,e_startTime,e_endTime,e_address,e_locationPic,e_slotQty,userId) Values (@e_date,@e_location, @e_startTime, @e_endTime, @e_address,@e_locationPic,@e_slotQty,@userId)";
                        //

                        //ori code
                        //string query = "Insert into Event(e_date,e_location,e_startTime,e_endTime,e_address,e_locationPic,e_slotQty) Values (@e_date,@e_location, @e_startTime, @e_endTime, @e_address,@e_locationPic,@e_slotQty)";
                        query += "SELECT SCOPE_IDENTITY()";
                        SqlCommand sqlcomm = new SqlCommand(query, con);
                        con.Open();

                        //added code 16nov [WORK]
                        sqlcomm.Parameters.AddWithValue("@userId", userId);
                        //
                        sqlcomm.Parameters.AddWithValue("@e_date", events.e_date);
                        sqlcomm.Parameters.AddWithValue("@e_location", events.e_location);
                        sqlcomm.Parameters.AddWithValue("@e_startTime", events.e_startTime);
                        sqlcomm.Parameters.AddWithValue("@e_endTime", events.e_endTime);
                        sqlcomm.Parameters.AddWithValue("@e_address", events.e_address);
                        sqlcomm.Parameters.AddWithValue("@e_slotQty", events.e_slotQty);
                        string filename = Path.GetFileNameWithoutExtension(events.ImageFile.FileName);
                        string extension = Path.GetExtension(events.ImageFile.FileName);
                        filename = filename + DateTime.Now.ToString("yymmssfff") + extension;
                        events.e_locationPic = "/Content/images/LocationUpload/" + filename;
                        filename = Path.Combine(Server.MapPath("~/Content/images/LocationUpload/"), filename);
                        events.ImageFile.SaveAs(filename);
                        sqlcomm.Parameters.AddWithValue("@e_locationPic", events.e_locationPic);
                    

                        if(events.e_endTime<events.e_startTime)
                        {
                            ViewBag.Alert = "WARNING: Start time shall be earlier than end time!";
                            con.Close();
                            return View();
                        }
                        else 
                        {
                            sqlcomm.ExecuteNonQuery();
                            ViewBag.Message = "REMINDER: New event has been successfully inserted!";
                            con.Close();
                            return View();
                        }
                    }

                }
                else
                {               
                    return View();               
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpGet]
        public ActionResult ModifyEvent(int id)
        {
            if (Convert.ToString(Session["userrole"]) == "Hospital Authority")
            {

                var eventDetail = new Event();
                String CS = ConfigurationManager.ConnectionStrings["con"].ConnectionString;
                using (SqlConnection con = new SqlConnection(CS))
                {
                    string query = "SELECT * FROM Event WHERE e_id = @e_id";
                    SqlCommand sqlcomm = new SqlCommand(query, con);
                    sqlcomm.Parameters.AddWithValue("@e_id", id);
                    con.Open();
                    SqlDataReader rdr = sqlcomm.ExecuteReader();

                    while (rdr.Read())
                    {
                        eventDetail.e_id = Convert.ToInt32(rdr["e_id"]);
                        eventDetail.e_date = Convert.ToDateTime(rdr["e_date"]);
                        eventDetail.e_location = rdr["e_location"].ToString();
                        eventDetail.e_startTime = Convert.ToDateTime(rdr["e_startTime"].ToString());
                        eventDetail.e_endTime = Convert.ToDateTime(rdr["e_endTime"].ToString());
                        eventDetail.e_address = rdr["e_address"].ToString();
                        eventDetail.e_slotQty = Convert.ToInt32(rdr["e_slotQty"]);
                    }
                    rdr.Close();
                    con.Close();
                    return View(eventDetail);
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

        }

        [HttpPost]
        public ActionResult ModifyEvent(Event events)
        {
            if (Convert.ToString(Session["userrole"]) == "Hospital Authority")
            {
                if (ModelState.IsValid)//if no this one ,event got error visual studio will show u also,need this
                {
                    String CS = ConfigurationManager.ConnectionStrings["con"].ConnectionString;
                    using (SqlConnection con = new SqlConnection(CS))
                    {
                        string query = "Update Event set e_date = @e_date , e_startTime = @e_startTime, e_endTime = @e_endTime, e_address = @e_address, e_slotQty=@e_slotQty WHERE e_id = @e_id";
                        SqlCommand sqlcomm = new SqlCommand(query, con);
                        sqlcomm.Parameters.AddWithValue("@e_id", events.e_id);
                        sqlcomm.Parameters.AddWithValue("@e_date", events.e_date);
                        sqlcomm.Parameters.AddWithValue("@e_startTime", events.e_startTime);
                        sqlcomm.Parameters.AddWithValue("@e_endTime", events.e_endTime);
                        sqlcomm.Parameters.AddWithValue("@e_address", events.e_address);
                        sqlcomm.Parameters.AddWithValue("@e_slotQty", events.e_slotQty);
                        con.Open();

                        if (events.e_endTime < events.e_startTime)
                        {
                            ViewBag.Alert = "WARNING: Start time shall be earlier than end time!";
                            con.Close();
                            return View();
                        }
                        else
                        {
                            sqlcomm.ExecuteNonQuery();
                            ViewBag.Message = "REMINDER: Event information have been updated!";
                            con.Close();
                            return View();
                        }
                    }
                }
                else
                {
                    ModifyEvent(events.e_id);
                    return View();
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

        }

        public ActionResult ViewEvent()
        {

            if (Convert.ToString(Session["userrole"]) == "Hospital Authority")
            {
                //latest 16nov [WORK]
                var userId = Session["userid"];
                //

                List<Event> eventList = new List<Event>();
                String CS = ConfigurationManager.ConnectionStrings["con"].ConnectionString;
                using (SqlConnection con = new SqlConnection(CS))
                {
                    //new code [WORK]
                    string query = "SELECT * FROM Event WHERE userId=@userId";
                    SqlCommand sqlcomm = new SqlCommand(query, con);
                    sqlcomm.Parameters.AddWithValue("@userId", userId);
                    //

                    //old
                    //SqlCommand cmd = new SqlCommand("SELECT * FROM Event", con);
                    //cmd.CommandType = CommandType.Text;
                    con.Open();

                    SqlDataReader rdr = sqlcomm.ExecuteReader();
                    while (rdr.Read())
                    {
                        var eventDetail = new Event();
                        eventDetail.e_id = Convert.ToInt32(rdr["e_id"]);
                        eventDetail.e_date = Convert.ToDateTime(rdr["e_date"]);
                        eventDetail.e_location = rdr["e_location"].ToString();
                        eventDetail.e_startTime = Convert.ToDateTime(rdr["e_startTime"].ToString());
                        eventDetail.e_endTime = Convert.ToDateTime(rdr["e_endTime"].ToString());
                        eventDetail.e_slotQty = Convert.ToInt32(rdr["e_slotQty"]);
                        eventDetail.e_address = rdr["e_address"].ToString();
                        eventList.Add(eventDetail);
                    }
                    rdr.Close();

Views/Authority/CreateEvent.cshtml
@model FYP_Blood.Models.Event


@{
    ViewBag.Title = "CreateEvent";
    Layout = "~/Views/Shared/_HospitalLayout.cshtml";
}

<head>
    <link href='https://fonts.googleapis.com/css?family=Quicksand' rel='stylesheet'>
    <link href="~/Content/Css/createEvent.css" rel="stylesheet" />
    @* datecontrol *@
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    @* Jquery Timepicker *@
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>


</head>


<div class="main-content">
    <div class="page">
        <div class="row p-3">
            <h3><span class="authority-title">Create Event</span></h3>
            <span class="authority-desc fw-bolder">Creation of blood donation event</span>
        </div>

        <div class="frame">

            @using (Html.BeginForm("CreateEvent", "Authority", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <table>
                    <tr style="width:789px;">
                        <td style="width:180px;"><b class="coltitle">Event Location</b></td>
                        <td style="width:15px;"><b>:</b></td>
                        <td>@Html.TextBoxFor(m => m.e_location, new { @class = "textbox", autocomplete = "off", @placeholder = "Please insert event location here..." })</td>
                        <td style="width:100px;">
                            @Html.ValidationMessageFor(m => m.e_location, "", new { @class = "text-danger" })
                        </td>
                    </tr>



                    <tr>
                        <td style="width: 160px; "><b class="coltitle">Location Image</b></td>
                        <td style="width:15px;"><b>:</b></td>
                        <td><input type="file" name="ImageFile" /></td>

                    </tr>

                    <tr>
                        <td><b class="coltitle">Event Date</b></td>
                        <td><b>:</b></td>
                        <td>@Html.TextBoxFor(m => m.e_date, new { @class = "textbox", @type = "date", @id = "dateControl" })</td>
                        <td>@Html.ValidationMessageFor(m => m.e_date, "", new { @class = "text-danger" })</td>

                    </tr>

                    <tr>
                        <td><b class="coltitle">Event Start Time</b></td>
                        <td><b>:</b></td>

                        <td>
                            @Html.TextBoxFor(m => m.e_startTime, new { @class = @"timepicker textbox", autocomplete = "off", @placeholder = "--:-- --", id = "starttime" })
                        </td>
                        <td>@Html.ValidationMessageFor(m => m.e_startTime, "", new { @class = "text-danger" })</td>
                    </tr>

                    <tr>
                        <td><b class="coltitle">Event End Time</b></td>
                        <td><b>:</b></td>

                        <td>
                            @Html.TextBoxFor(m => m.e_endTime, new { @class = @"timepicker textbox", autocomplete = "off", @placeholder = "--:-- --", id = "endtime" })

                        </td>
                        <td>@Html.ValidationMessageFor(m => m.e_endTime, "", new { @class = "text-danger" })</td>

                    </tr>

                    <tr>
                        <td><b class="coltitle">Event Slot Quantity</b></td>
                        <td><b>:</b></td>

                        <td>
                            @Html.TextBoxFor(m => m.e_slotQty, new { @class = "textbox", autocomplete = "off", @placeholder = "Please enter the quantity of time slot...", @type = "number" })
                        </td>
                        <td>@Html.ValidationMessageFor(m => m.e_slotQty, "", new { @class = "text-danger" })</td>

                    </tr>

                    <tr>
                        <td class="addressTitle"><b class="coltitle">Event Address</b></td>
                        <td class="addressTitle"><b>:</b></td>
                        <td>
                            @Html.TextAreaFor(m => m.e_address, new { @class = "textboxAdd", @type = "text", @placeholder = "Please insert event address here..." })
                        </td>

                        <td style="width:150px">
                            @Html.ValidationMessageFor(m => m.e_address, "", new { @class = "text-danger" })
                            <button class="createEventBtn" type="submit" value="submit">CREATE EVENT</button>
                        </td>

                    </tr>
                </table>



            }

            @if (ViewBag.Alert != null)
            {
                <script type="text/javascript">
                        window.onload = function () {
                                alert("@ViewBag.Alert");
                                window.location.href = '@Url.Action("CreateEvent", "Authority")';
                    };
                </script>
            }


            @if (ViewBag.Message != null)
            {
                <script type="text/javascript">
                        window.onload = function () {
                                alert("@ViewBag.Message");
                                window.location.href = '@Url.Action("ViewEvent", "Authority")';
                    };
                </script>
            }

        </div>
    </div>
</div>

<script>
    $('.timepicker').timepicker({
        timeFormat: 'h:mm p',
        interval: 30,
        minTime: '8:00am',
        maxTime: '10:00pm',
        startTime: '8:00',
        dynamic: false,
        dropdown: true,
        scrollbar: true,

    });

    $(document).ready(function () {

        var dtToday = new Date();

        var month = dtToday.getMonth() + 1;
        var day = dtToday.getDate();
        var year = dtToday.getFullYear();
        if (month < 10)
            month = '0' + month.toString();
        if (day < 10)
            day = '0' + day.toString();

        var maxDate = year + '-' + month + '-' + day;

        $('#dateControl').attr('min', maxDate);
    })

</script>



Views/Authority/ManageApptList.cshtml
@model IEnumerable<FYP_Blood.Models.Appointment>

@{
    ViewBag.Title = "ManageApptList";
    Layout = "~/Views/Shared/_HospitalLayout.cshtml";

}

<head>
    <link href='https://fonts.googleapis.com/css?family=Quicksand' rel='stylesheet'>
    <link href="~/Content/Css/manageApptList.css" rel="stylesheet" />
</head>


<div class="main-content">
    <div class="page">
        <div class="row p-3">
            <h3><span class="authority-title">Appointment List</span></h3>
            <span class="authority-desc fw-bolder">Manage blood donation appointment compleness.</span>
        </div>

        <div>
            <table class="apptTbl">
                <tr class="colName titlebackground">
                    <th class="contexttitle" style="padding-left: 20px;">Appointment ID</th>
                    @*<th class="contexttitle">USER ID</th>*@ @*ADD ON USER ID EASIER TO CHECK*@
                    <th class="contexttitle" style="padding-left: 20px;">Event Location</th>
                    <th class="contexttitle" style="text-align:center;">Donation Date</th>
                    <th class="contexttitle" style="text-align:center;">Time Slot</th>
                    <th class="contexttitle" style="text-align:center;">Status</th>
                    <th class="contexttitle" style="text-align:center;">Action</th>

                </tr>



                @foreach (var appt in Model)
                {
                    <tr class="colName">

                        <td class="context" style="width:145px;"><b>@appt.apptId</b></td>
                        @*<td class="context" style="width:93px;">@appt.userId</td>*@@*ADD ON USER ID EASIER TO CHECK*@
                        <td class="context" style="width:350px;text-align:left;padding-left:20px;">@appt.e_location</td>
                        <td class="context" style="width: 150px; text-align: center;">@appt.eventdate.ToString("dd MMM yyyy")</td>
                        <td class="context" style="width: 150px; text-align: center;">@appt.apptTimeSlot</td>
                        <td class="context" style="width: 120px; text-align: center;">@appt.status</td>
                        <td class="editIconFrame"><button class="editbutton" onclick="location.href='@Url.Action("UpdateDonationStatus", "Authority", new { id = appt.apptId })'"><i class="fa fa-pencil-square-o fa-lg editIcon" aria-hidden="true"></i></button></td>

                    </tr>
                }

            </table>
        </div>
    </div>
</div>

Views/Authority/ModifyEvent.cshtml
@model FYP_Blood.Models.Event
@{
    ViewBag.Title = "ModifyEvent";
    Layout = "~/Views/Shared/_HospitalLayout.cshtml";

}

<head>
    <link href='https://fonts.googleapis.com/css?family=Quicksand' rel='stylesheet'>
    <link href="~/Content/Css/modifyEvent.css" rel="stylesheet" />

    @* datecontrol *@
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    @* Jquery Timepicker *@
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>


</head>

<div class="main-content">
    <div class="page">
        <div class="row p-3">
            <h3><span class="authority-title">Modify Event</span></h3>
            <span class="authority-desc fw-bolder">Modification of blood donation event.</span>
        </div>

        <div class="frame">
            @using (Html.BeginForm("ModifyEvent", "Authority", FormMethod.Post))
            {

                <table>
                    @* if not data dun want to display use hiddenfor, displayfor only display could not pass data to controller *@
                    @Html.HiddenFor(m => m.e_id)
                    @Html.HiddenFor(m => m.e_location)
                    <tr>
                        <td class="colwidth"><b class="coltitle">Event ID</b></td>
                        <td style="width:18px;"><b>:</b></td>
                        <td><span><b>@Html.DisplayFor(m => m.e_id)</b></span><br />
                    </tr>

                    <tr>
                        <td class="colwidth"><b class="coltitle">Event Location</b></td>
                        <td style="width:18px;"><b>:</b></td>
                        <td><span><b>@Html.DisplayFor(m => m.e_location)</b></span><br />
                    </tr>

                    <tr>
                        <td><b class="coltitle">Event Date</b></td>
                        <td><b>:</b></td>
                        <td>@Html.TextBoxFor(m => m.e_date, "{0:yyyy-MM-dd}", new { @class = "textbox", type = "date", @name = "eventDate", @id = "datecontrol" })</td>
                        <td>@Html.ValidationMessageFor(m => m.e_date, "", new { @class = "text-danger" })</td>

                    </tr>


                    <tr>
                        <td><b class="coltitle">Event Start Time</b></td>
                        <td><b>:</b></td>
                        <td>
                            @Html.TextBoxFor(m => m.e_startTime, "{0:hh:mm tt}", new { @class = @"timepicker textbox", @id = "startTime" })
                        </td>
                        <td>@Html.ValidationMessageFor(m => m.e_startTime, "", new { @class = "text-danger" })</td>



                    </tr>

                    <tr>
                        <td><b class="coltitle">Event End Time</b></td>
                        <td><b>:</b></td>
                        <td>
                            @Html.TextBoxFor(m => m.e_endTime, "{0:hh:mm tt}", new { @class = @"timepicker textbox", @id = "endTime" })
                        </td>
                        <td>@Html.ValidationMessageFor(m => m.e_endTime, "", new { @class = "text-danger" })</td>
                    </tr>

                    <tr>
                        <td><b class="coltitle">Event Slot Quantity</b></td>
                        <td><b>:</b></td>

                        <td>
                            @Html.TextBoxFor(m => m.e_slotQty, new { @class = "textbox", @type = "number" })
                        </td>
                        <td>@Html.ValidationMessageFor(m => m.e_slotQty, "", new { @class = "text-danger" })</td>
                    </tr>

                    <tr>
                        <td class="addressTitle"><b class="coltitle">Event Address</b></td>
                        <td class="addressTitle"><b>:</b></td>
                        <td>
                            @Html.TextAreaFor(m => m.e_address, new { @class = "textboxAdd", @type = "text" })
                        </td>
                        <td style="width:150px">
                            @Html.ValidationMessageFor(m => m.e_address, "", new { @class = "text-danger" })
                            <button class="modifyEventBtn">SAVE EVENT</button>
                        </td>
                    </tr>
                </table>
            }


            @if (ViewBag.Alert != null)
            {
                <script type="text/javascript">
                    window.onload = function () {
                        alert("@ViewBag.Alert");
                        window.location.href = '@Url.Action("ModifyEvent", "Authority")';
                    };
                </script>
            }




            @if (ViewBag.Message != null)
            {
                <script type="text/javascript">
                window.onload = function () {

                         alert("@ViewBag.Message");
                        window.location.href = '@Url.Action("ViewEvent", "Authority")';

                        var data = sessionStorage.getItem('clicked');
                        if (data == 'true') {
                            $("#quality-records-container").css("display", "block");
                            sessionStorage.setItem('clicked', true);
                        }
                    };
                </script>
            }
        </div>
    </div>
</div>

<script>
    $('.timepicker').timepicker({
        timeFormat: 'h:mm p',
        interval: 30,
        minTime: '8:00am',
        maxTime: '10:00pm',
        startTime: '8:00',
        dynamic: false,
        dropdown: true,
        scrollbar: true,

    });

    $(document).ready(function () {

        var dtToday = new Date();

        var month = dtToday.getMonth() + 1;
        var day = dtToday.getDate();
        var year = dtToday.getFullYear();
        if (month < 10)
            month = '0' + month.toString();
        if (day < 10)
            day = '0' + day.toString();

        var maxDate = year + '-' + month + '-' + day;

        $('#datecontrol').attr('min', maxDate);
    })
</script>

Views/Authority/ReportDateSelection.cshtml
@model FYP_Blood.Models.Event



@using (Html.BeginForm("TotalUserReport", "Authority", FormMethod.Post))
{
    <table>
        <tr>
            <td class="firstRow fixedItem">START DATE</td>
            <td class="colon fixedItem">:</td>
            <td>
                @Html.TextBoxFor(m => m.ev_startdate, new { @class = "textbox", @type = "date", @id = "startdate", @style = "margin-left:-60px;margin-right:20px;" })
            </td>
            <td class="space"></td>
            <td class="firstRow fixedItem">END DATE</td>
            <td class="colon fixedItem">:</td>
            <td>
                @Html.TextBoxFor(m => m.ev_enddate, new { @class = "textbox", @type = "date", @id = "enddate", @style = "margin-left:-60px;margin-right:50px;" })
            </td>
            <td> <button class="viewReportBtn  btn-authority" style="width:185px;" type="submit" onclick="validate()">VIEW REPORT</button></td>
        </tr>
    </table>

    <script>
            function validate() {
                var startdate = document.getElementById("startdate").value;
                var enddate = document.getElementById("enddate").value;
                if (startdate == "" || enddate == "") {
                    alert("REMINDER: Start date or end date cannot be blank!");
                    return false;
                }
                else
                {
                    window.location.href = '@Url.Action("TotalUserReport", "Authority")';
                }
            }
    </script>
}


Views/Authority/ReportSelection.cshtml

@{
    ViewBag.Title = "ReportSelection";
    Layout = "~/Views/Shared/_HospitalLayout.cshtml";
}

<head>
    <link href="~/Content/Css/reportSelection.css" rel="stylesheet" />
</head>

<div class="main-content">
    <div class="row p-3">
        <h3><span class="authority-title">View Report</span></h3>
        <span class="authority-desc fw-bolder">Prompt the selection of report type.</span>
    </div>
   
    <div>
        <div class="ReportType">
            <button class="reportBtn" style="margin-left:20px;" onclick="location.href='@Url.Action("TotalUserReport", "Authority")'"><i class="fa fa-address-book subTitleICon" aria-hidden="true"></i> Total User Registered for Blood Donation</button>
        </div>
    </div>
</div>



Views/Authority/UpdateDonationStatus.cshtml
@model FYP_Blood.Models.Appointment
@{
    ViewBag.Title = "UpdateDonationStatus";
    Layout = "~/Views/Shared/_HospitalLayout.cshtml";

}

<head>
    <link href='https://fonts.googleapis.com/css?family=Quicksand' rel='stylesheet'>
    <link href="~/Content/Css/updateDonationStatus.css" rel="stylesheet" />
</head>

<div class="main-content">
    <div>
        <div class="row p-3">
            <h3><span class="authority-title">Blood Quality Tracking</span></h3>
            <span class="authority-desc fw-bolder">Make admendment of the status of donor.</span>
        </div>


        <div class="frame">
            @using (Html.BeginForm("UpdateDonationStatus", "Authority", FormMethod.Post))
            {
                @Html.HiddenFor(m => m.apptId)
                @Html.HiddenFor(m => m.eventdate)
                @Html.HiddenFor(m => m.apptTimeSlot)
                <table>
                    <tr>
                        <td class="colwidth"><b class="coltitle">Donor ID</b></td>
                        <td style="width:18px;"><b>:</b></td>
                        <td><span><b>@Html.DisplayFor(m => m.apptId)</b></span><br />
                    </tr>

                    <tr>
                        <td class="colwidth"><b class="coltitle">Donation Date</b></td>
                        <td style="width:18px;"><b>:</b></td>
                        <td><span><b>@Html.DisplayFor(m => m.eventdate)</b></span><br />
                    </tr>


                    <tr>
                        <td class="colwidth"><b class="coltitle">Donation Date</b></td>
                        <td style="width:18px;"><b>:</b></td>
                        <td><span><b>@Html.DisplayFor(m => m.e_location)</b></span><br />
                    </tr>

                    <tr>
                        <td class="colwidth"><b class="coltitle">Donation Time Slot</b></td>
                        <td style="width:18px;"><b>:</b></td>
                        <td><span><b>@Html.DisplayFor(m => m.apptTimeSlot)</b></span><br />
                    </tr>

                    <tr>
                        <td class="colwidth"><b class="coltitle">Donation Status</b></td>
                        <td style="width:18px;"><b>:</b></td>
                        <td>
                            @Html.RadioButtonFor(m => m.status, "Pending", new { @class = "radioformat" })<b>Pending</b>
                            @Html.RadioButtonFor(m => m.status, "Completed", new { @class = "radioformat1" })<b>Completed</b>
                            <br />
                    </tr>

                    <tr>
                        <td style="width:150px" colspan="3">
                            <button class="saveChangesBtn" type="submit">SAVE CHANGES</button>
                        </td>
                    </tr>


                </table>
            }

            @if (ViewBag.Message != null)
            {
                <script type="text/javascript">
                        window.onload = function () {
                                alert("@ViewBag.Message");
                                window.location.href = '@Url.Action("ManageApptList", "Authority")';
                    };
                </script>
            }
        </div>

    </div>
</div>